#!/bin/bash

# Exit on any errors
set -e

source $OPENSHIFT_CARTRIDGE_SDK_BASH

list=
kvargs=$(echo "${@:4}" | tr -d "\n" )
for arg in $kvargs; do
    ip=$(echo "$arg" | cut -f 2 -d '=' | tr -d "'")
    if [ -z "$list" ]; then
        list="$ip"
    else
        list="$list $ip"
    fi
done

echo $list > $OPENSHIFT_VERTX_DIR/env/OPENSHIFT_VERTX_HAZELCAST_CLUSTER
